sonar.projectKey=procunex-enterprise
sonar.projectName=Procunex Enterprise
sonar.sources=apps/api/src,apps/web/app,apps/web/components,apps/web/lib
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/uploads/**
sonar.coverage.exclusions=**/node_modules/**,**/.next/**,**/dist/**
sonar.javascript.lcov.reportPaths=
sonar.sourceEncoding=UTF-8
