import { Injectable, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';

@Injectable()
export class ReplenishmentService {
  constructor(private readonly prisma: PrismaService) {}

  // Products at/below reorder point → suggested purchase quantities
  async suggestions(tenantId: string) {
    const rows: any[] = await this.prisma.$queryRaw`
      SELECT p.id, p.name, p.sku, p.unit, p."currentStock", p."reorderPoint",
             p."maxStock", p."reorderQuantity", p."costPrice", p."vendorId",
             v.name AS "vendorName"
      FROM "Product" p
      LEFT JOIN "Vendor" v ON p."vendorId" = v.id
      WHERE p."tenantId" = ${tenantId}
        AND p."isActive" = true
        AND p."reorderPoint" > 0
        AND p."currentStock" <= p."reorderPoint"
      ORDER BY (p."currentStock" / NULLIF(p."reorderPoint", 0)) ASC
    `;

    const data = rows.map((r) => {
      const topUp = r.maxStock > r.currentStock ? r.maxStock - r.currentStock : 0;
      const suggestedQty = Math.round((Math.max(topUp, r.reorderQuantity || 0, 0)) * 1e6) / 1e6;
      return {
        productId: r.id,
        name: r.name,
        sku: r.sku,
        unit: r.unit,
        currentStock: r.currentStock,
        reorderPoint: r.reorderPoint,
        suggestedQty,
        costPrice: r.costPrice,
        estimatedCost: Math.round(suggestedQty * (r.costPrice || 0) * 100) / 100,
        vendorId: r.vendorId,
        vendorName: r.vendorName,
      };
    });

    return { data };
  }

  private async generateRequestNumber(tenantId: string): Promise<string> {
    const today = new Date();
    const prefix = `PR-${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, '0')}${String(today.getDate()).padStart(2, '0')}`;
    const count = await this.prisma.purchaseRequest.count({
      where: { tenantId, requestNumber: { startsWith: prefix } },
    });
    return `${prefix}-${String(count + 1).padStart(4, '0')}`;
  }

  // Create a DRAFT purchase request from selected low-stock items
  async generate(tenantId: string, userId: string, body: any) {
    const requested: Array<{ productId: string; quantity: number }> = Array.isArray(body?.items) ? body.items : [];
    if (requested.length === 0) throw new BadRequestException('No items selected for replenishment');

    const products = await this.prisma.product.findMany({
      where: { tenantId, id: { in: requested.map((r) => r.productId) } },
      select: { id: true, name: true, sku: true, unit: true, costPrice: true, vendorId: true },
    });
    const byId = new Map(products.map((p) => [p.id, p]));

    let totalAmount = 0;
    const items = requested
      .filter((r) => byId.has(r.productId) && r.quantity > 0)
      .map((r, i) => {
        const p = byId.get(r.productId)!;
        const estimatedPrice = p.costPrice || 0;
        const totalPrice = Math.round(r.quantity * estimatedPrice * 100) / 100;
        totalAmount += totalPrice;
        return {
          itemNumber: i + 1,
          description: `${p.name} (${p.sku})`,
          uom: p.unit || 'pcs',
          quantity: r.quantity,
          estimatedPrice,
          totalPrice,
          productId: p.id,
          vendorId: p.vendorId || null,
        };
      });

    if (items.length === 0) throw new BadRequestException('No valid items to replenish');

    const requestNumber = await this.generateRequestNumber(tenantId);
    const today = new Date();

    return this.prisma.purchaseRequest.create({
      data: {
        tenantId,
        requestNumber,
        title: `Auto-replenishment ${today.toISOString().slice(0, 10)}`,
        description: 'Generated from low-stock reorder points',
        requestedById: userId,
        priority: 'MEDIUM',
        status: 'DRAFT',
        totalAmount: Math.round(totalAmount * 100) / 100,
        notes: 'Auto-generated by replenishment monitor',
        items: { create: items },
      },
      include: { items: true },
    });
  }
}
